### ISSUE TITLE
Zombie horses are not mountable therefore untameable

### ISSUE THREAD

**Issue by NRobbo** [BoltyDawg/HorseOverhaul#21]
pretty self explanatory really.

using the newest beta build

**Comment by BoltyDawg** [comment]
You can actually spawn in a tamed zombie horse by using the following command:
`/summon minecraft:zombie_horse ~ ~ ~ {Tame:1b}`
Doing so allows you to mount the horse and access all the other features of the plugin with said zombie horse. However, there's nothing you can do to make them breed. Maybe I could add that as a reach goal but that would be complicated.

Since this is just part of the game's design I'm not sure I should address it with my plugin, since my plugin already performs as expected with zombie horses. It's just one of those weird things in this game. 

If there's something you think would make for a good feature relating to zombie horses do lmk, but since these guys can only be spawned in with commands I don't see much of a need for me to add any functionality for this specific oddity, especially since it can be addressed with the in game commands required to spawn one in the first place.
